backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

# editorial workflow allows posts to have an "in review" status
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

# Collections contain the different types of content we will create and publish
collections:
  - name: "blog"
    label: "Blog"
    folder: "website/src/posts"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # We will use the hidden templateKey field to map files to their corresponding template
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "events"
    label: "Events"
    folder: "website/src/events"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      # We will use the hidden templateKey field to map files to their corresponding template
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "event-post",
        }
      - { label: "Event Name", name: "title", widget: "string" }
      - { label: "Featured Event", name: "featured", widget: "boolean", default: false }
      - {
          label: "Event Type",
          name: "type",
          widget: "select",
          default: ["The New Developers"],
          options: ["The New Developers", "Community"],
        }
      - { label: "When", name: "date", widget: "datetime" }
      - { label: "Where", name: "where", widget: "string" }
      - { label: "Details", name: "body", widget: "markdown" }
      - {
          label: "Registration Link",
          name: "link",
          widget: "string",
          hint: "This should link to your external registration page.",
          required: false,
        }
      - {
        label: "Author",
        name: "author",
        widget: "string",
        hint: "This should be a few characters long to identify you."
      }

  - name: "opportunities"
    label: "Opportunities"
    folder: "website/src/opportunities"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
        label: "Template Key",
        name: "templateKey",
        widget: hidden,
        default: "opportunities-post"
      }
      - { label: "Title", name: "title", widget: "string", hint: "The job title or name of the opportunity" }
      - { label: "Publish date", name: "date", widget: datetime }
      - { label: "Name of Organization", name: "organization", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Show post", name: "show", widget: "boolean", default: true }
      - { label: "Description", name: "body", widget: "markdown", hint: "Please describe the opportunity" }
      - { label: "Compensation", name: "compensation", widget: "string", hint: "Is this a salaried position? Volunteer? Is there equit involved?" }
      - { label: "Contact Information", name: "contactInfo", widget: "text" }
      - { label: "Organization Website", name: "organizationWebsite", widget: "string", required: false }



